language: java

jdk: oraclejdk8

install:
  - chmod +x gradlew
  - ./gradlew assemble
script:
  - chmod +x gradlew
  - ./gradlew build
  - java -jar WordCount-1.0-SNAPSHOT-all.jar
  - java -jar WordCount-1.0-SNAPSHOT-all.jar -r test.txt
